using PokemonDataAccess;
using PokemonDataAccess.Models;

namespace PokeCommon.Utils
{
    public static class PokemonToolsWithoutDBNorm
    {
        // Generated by Copilot
        // TODO: 整一个本地数据源
        // 整一个本地数据源


        private static Dictionary<int, Ability> _abilities { get; set; } = new();
        private static Dictionary<string, int> _abilityNameId { get; set; } = new();

        private static Dictionary<int, Move> _moves { get; set; } = new();
        private static Dictionary<string, int> _moveNameId { get; set; } = new();

        private static Dictionary<int, Pokemon> _pokemons { get; set; } = new();
        //private static Pokemon[] _pokemons { get; set; } = new Pokemon[4000];
        private static Dictionary<string, int> _pokemonNameId { get; set; } = new();
        private static Dictionary<int, Item> _items { get; set; } = new();
        //private static Item[] _items { get; set; } = new Item[2000];
        private static Dictionary<string, int> _itemNameId { get; set; } = new();

        private static Dictionary<string, int> _psPokemonId { get; set; } = new();
        private static Dictionary<int, PSPokemon> _pokemonIdPSName { get; set; } = new();

        private static Dictionary<int, Nature> _natures { get; set; } = new();
        private static Dictionary<string, int> _natureNameId { get; set; } = new();

        private static Dictionary<int, PokeType> _pokeTypes { get; set; } = new();
        private static Dictionary<string, int> _pokeTypeNameId { get; set; } = new();

        /// <summary>
        /// 标准化字符串：移除空格并转换为小写
        /// </summary>
        /// <param name="input">输入字符串</param>
        /// <returns>标准化后的字符串</returns>
        public static string NormalizeString(string input)
        {
            return input?.Replace(" ", "").Replace("-", "").ToLowerInvariant() ?? string.Empty;
        }

        public static async ValueTask<PokeType?> GetTypeAsync(int id)
        {
            if (_pokeTypes.TryGetValue(id, out var type))
            {
                return type;
            }
            else
            {
                var nType = PokemonDBInMemory.Types.Find(s => s.Id == id);
                if (nType != null)
                {
                    _pokeTypes.TryAdd(id, nType);
                    _pokeTypeNameId.TryAdd(nType.Name_Chs, id);
                    _pokeTypeNameId.TryAdd(nType.Name_Eng, id);
                    _pokeTypeNameId.TryAdd(nType.Name_Jpn, id);
                    return nType;
                }
                else
                {
                    return null;
                }
            }
        }
        public static async ValueTask<PokeType?> GetTypeAsync(string name)
        {
            var normalizedName = NormalizeString(name);
            if (_pokeTypeNameId.TryGetValue(normalizedName, out var type))
            {
                return await GetTypeAsync(type);
            }
            else
            {
                {
                    var nType = PokemonDBInMemory.Types.FirstOrDefault
                        (n => NormalizeString(n.Name_Chs) == normalizedName || 
                              NormalizeString(n.Name_Eng) == normalizedName || 
                              NormalizeString(n.Name_Jpn) == normalizedName);
                    if (nType != null)
                    {
                        _pokeTypes.TryAdd(nType.Id, nType);
                        _pokeTypeNameId.TryAdd(NormalizeString(nType.Name_Chs), nType.Id);
                        _pokeTypeNameId.TryAdd(NormalizeString(nType.Name_Eng), nType.Id);
                        _pokeTypeNameId.TryAdd(NormalizeString(nType.Name_Jpn), nType.Id);
                        return nType;
                    }
                    else
                    {
                        return null;
                    }
                }
            }
        }
        public static async ValueTask<Nature?> GetNatureAsync(int id)
        {
            if (_natures.TryGetValue(id, out var nature))
            {
                return nature;
            }
            else
            {
                var nNature = PokemonDBInMemory.Natures.Find(s => s.NatureId == id);
                if (nNature != null)
                {
                    _natures.TryAdd(id, nNature);
                    _natureNameId.TryAdd(nNature.Name_Chs, id);
                    _natureNameId.TryAdd(nNature.Name_Eng, id);
                    _natureNameId.TryAdd(nNature.Name_Jpn, id);
                    return nNature;
                }
                else
                {
                    return null;
                }
            }
        }
        public static async ValueTask<Nature?> GetNatureAsync(string name)
        {
            var normalizedName = NormalizeString(name);
            if (_natureNameId.TryGetValue(normalizedName, out var id))
            {
                return await GetNatureAsync(id);
            }
            else
            {
                {

                    var nNature = PokemonDBInMemory.Natures
                            .FirstOrDefault(n => NormalizeString(n.Name_Chs) == normalizedName || 
                                                 NormalizeString(n.Name_Eng) == normalizedName || 
                                                 NormalizeString(n.Name_Jpn) == normalizedName);
                    if (nNature != null)
                    {
                        _natures.TryAdd(nNature.NatureId, nNature);
                        _natureNameId.TryAdd(NormalizeString(nNature.Name_Chs), nNature.NatureId);
                        _natureNameId.TryAdd(NormalizeString(nNature.Name_Eng), nNature.NatureId);
                        _natureNameId.TryAdd(NormalizeString(nNature.Name_Jpn), nNature.NatureId);
                        return nNature;
                    }
                    else
                    {
                        return null;
                    }
                }
            }
        }

        public static async ValueTask<Pokemon?> GetPokemonFromPsNameAsync(string name)
        {
            var normalizedName = NormalizeString(name);
            if (_psPokemonId.TryGetValue(normalizedName, out var id))
            {
                return await GetPokemonAsync(id);
            }
            else
            {
                {

                    var nPSPoke = PokemonDBInMemory.PSPokemons.FirstOrDefault(p => NormalizeString(p.PSName) == normalizedName);
                    if (nPSPoke != null)
                    {
                        // Todo: 为啥要try
                        _psPokemonId.TryAdd(normalizedName, nPSPoke.PokemonId ?? 0);
                        return GetPokemonAsync(nPSPoke.PokemonId ?? 0).Result;
                    }
                    else
                    {
                        return null;
                    }
                }
            }
        }

        //static object lockdb = new object();
        public static async ValueTask<PSPokemon?> GetPsPokemonAsync(int pokemonId)
        {
            if (_pokemonIdPSName.TryGetValue(pokemonId, out var name))
            {
                return name;
            }
            else
            {
                PSPokemon? nPSName;
                {
                    nPSName = PokemonDBInMemory.PSPokemons.FirstOrDefault(s => s.PokemonId == pokemonId);
                    if (nPSName != null)
                    {
                        _pokemonIdPSName.TryAdd(pokemonId, nPSName);
                    }
                }


                return nPSName;
            }
        }

        /// <summary>
        /// 获取特性
        /// </summary>
        /// <param name="name"></param>
        /// <returns></returns>
        public static async ValueTask<Ability?> GetAbilityAsync(string name)
        {
            var normalizedName = NormalizeString(name);
            if (_abilityNameId.TryGetValue(normalizedName, out var abilityId))
            {
                return await GetAbilityAsync(abilityId);
            }
            else
            {
                {

                    var nAbility = PokemonDBInMemory.Abilities.FirstOrDefault(s => NormalizeString(s.Name_Chs) == normalizedName || 
                                                                                 NormalizeString(s.Name_Eng) == normalizedName || 
                                                                                 NormalizeString(s.Name_Jpn) == normalizedName);
                    if (nAbility != null)
                    {
                        _abilities[nAbility.AbilityId] = nAbility;
                        _abilityNameId[NormalizeString(nAbility.Name_Chs)] = nAbility.AbilityId;
                        _abilityNameId[NormalizeString(nAbility.Name_Jpn)] = nAbility.AbilityId;
                        _abilityNameId[NormalizeString(nAbility.Name_Eng)] = nAbility.AbilityId;
                    }
                    return nAbility;
                }
            }

        }
        /// <summary>
        /// 获取特性
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public static async ValueTask<Ability?> GetAbilityAsync(int id)
        {
            if (_abilities.TryGetValue(id, out var ability))
            {
                return ability;
            }
            else
            {
                var nAbility = PokemonDBInMemory.Abilities.FirstOrDefault(s => s.AbilityId == id);
                if (nAbility != null)
                {
                    _abilities[nAbility.AbilityId] = nAbility;
                    _abilityNameId[NormalizeString(nAbility.Name_Chs)] = nAbility.AbilityId;
                    _abilityNameId[NormalizeString(nAbility.Name_Jpn)] = nAbility.AbilityId;
                    _abilityNameId[NormalizeString(nAbility.Name_Eng)] = nAbility.AbilityId;
                }
                return nAbility;
            }

        }

        public static async ValueTask<Move?> GetMoveAsync(string name)
        {
            var normalizedName = NormalizeString(name);
            if (_moveNameId.TryGetValue(normalizedName, out var moveId))
            {
                return await GetMoveAsync(moveId);
            }
            else
            {
                {

                    var nMove = PokemonDBInMemory.Moves.FirstOrDefault(s => NormalizeString(s.Name_Chs) == normalizedName || 
                                                                          NormalizeString(s.Name_Eng) == normalizedName || 
                                                                          NormalizeString(s.Name_Jpn) == normalizedName);
                    if (nMove != null)
                    {
                        _moves[nMove.MoveId] = nMove;
                        _moveNameId[NormalizeString(nMove.Name_Chs)] = nMove.MoveId;
                        _moveNameId[NormalizeString(nMove.Name_Jpn)] = nMove.MoveId;
                        _moveNameId[NormalizeString(nMove.Name_Eng)] = nMove.MoveId;
                    }
                    return nMove;
                }
            }
        }
        /// <summary>
        /// 获取招式
        /// </summary>
        public static async ValueTask<Move?> GetMoveAsync(int id)
        {
            if (_moves.TryGetValue(id, out var move))
            {
                return move;
            }
            else
            {
                var nMove = PokemonDBInMemory.Moves.Find(s => s.MoveId == id);
                if (nMove != null)
                {
                    _moves[nMove.MoveId] = nMove;
                    _moveNameId[NormalizeString(nMove.Name_Chs)] = nMove.MoveId;
                    _moveNameId[NormalizeString(nMove.Name_Jpn)] = nMove.MoveId;
                    _moveNameId[NormalizeString(nMove.Name_Eng)] = nMove.MoveId;
                }
                return nMove;
            }
        }

        public static async ValueTask<Pokemon?> GetPokemonAsync(string name)
        {
            var normalizedName = NormalizeString(name);
            if (_pokemonNameId.TryGetValue(normalizedName, out var pokemonId))
            {
                return await GetPokemonAsync(pokemonId);
            }
            else
            {
                var nPokemon = PokemonDBInMemory.Pokemons.FirstOrDefault(s => NormalizeString(s.NameChs) == normalizedName || 
                                                                            NormalizeString(s.NameEng) == normalizedName || 
                                                                            NormalizeString(s.NameJpn) == normalizedName);
                if (nPokemon != null)
                {
                    _pokemons[nPokemon.Id] = nPokemon;
                    _pokemonNameId[NormalizeString(nPokemon.NameChs)] = nPokemon.Id;
                    _pokemonNameId[NormalizeString(nPokemon.NameJpn)] = nPokemon.Id;
                    _pokemonNameId[NormalizeString(nPokemon.NameEng)] = nPokemon.Id;
                }
                return nPokemon;
            }
        }
        public static async ValueTask<Pokemon?> GetPokemonAsync(int id)
        {
            if (_pokemons.TryGetValue(id, out var pokemon))
            {
                return pokemon;
            }
            else
            {
                var nPokemon = PokemonDBInMemory.Pokemons.FirstOrDefault(s => s.Id == id);
                if (nPokemon != null)
                {
                    _pokemons[nPokemon.Id] = nPokemon;
                    _pokemonNameId.TryAdd(NormalizeString(nPokemon.NameChs ?? string.Empty), nPokemon.Id);
                    _pokemonNameId.TryAdd(NormalizeString(nPokemon.NameJpn ?? string.Empty), nPokemon.Id);
                    _pokemonNameId.TryAdd(NormalizeString(nPokemon.NameEng ?? string.Empty), nPokemon.Id);
                }
                return nPokemon;
            }
        }
        public static async ValueTask<Item?> GetItemAsync(string name)
        {
            var normalizedName = NormalizeString(name);
            if (_itemNameId.TryGetValue(normalizedName, out var itemId))
            {
                return await GetItemAsync(itemId);
            }
            else
            {


                    var nItem = PokemonDBInMemory.Items.FirstOrDefault(s => NormalizeString(s.Name_Chs) == normalizedName || 
                                                                          NormalizeString(s.Name_Eng) == normalizedName || 
                                                                          NormalizeString(s.Name_Jpn) == normalizedName);
                    if (nItem != null)
                    {
                        _items[nItem.ItemId] = nItem;
                        _itemNameId[NormalizeString(nItem.Name_Chs)] = nItem.ItemId;
                        _itemNameId[NormalizeString(nItem.Name_Jpn)] = nItem.ItemId;
                        _itemNameId[NormalizeString(nItem.Name_Eng)] = nItem.ItemId;
                    }
                    return nItem;
                
            }
        }
        public static async ValueTask<Item?> GetItemAsync(int id)
        {
            if (_items.TryGetValue(id, out var item))
            //if (_items[id] != null)
            {
                //return _items[id];
                return item;
            }
            else
            {
                var nItem = PokemonDBInMemory.Items.Find(s => s.ItemId == id);
                if (nItem != null)
                {
                    _items[nItem.ItemId] = nItem;
                    _itemNameId[NormalizeString(nItem.Name_Chs)] = nItem.ItemId;
                    _itemNameId[NormalizeString(nItem.Name_Jpn)] = nItem.ItemId;
                    _itemNameId[NormalizeString(nItem.Name_Eng)] = nItem.ItemId;
                }
                return nItem;
            }
        }

    }
}
