// Generated by Copilot
using System.Net.WebSockets;
using System.Text;
using System.Text.Json;
using PSClient.Battle;
using PSClient.Models;

namespace PSClient.Client;

/// <summary>
/// 消息类型枚举
/// </summary>
internal enum MessageType
{
    Receive,
    Send,
}

/// <summary>
/// Pokemon Showdown 客户端
/// </summary>
public partial class SDClient : IDisposable
{
    #region Events

    /// <summary>
    /// 用户信息更新事件
    /// </summary>
    public event Action? OnUserUpdate;

    /// <summary>
    /// 挑战事件（参数：挑战者ID, 规则）
    /// </summary>
    public event Action<string, string>? OnChallenge;

    /// <summary>
    /// 聊天事件（参数：用户ID, 消息）
    /// </summary>
    public event Action<string, string>? OnChat;

    /// <summary>
    /// 请求动作事件
    /// </summary>
    public event Action<PSBattle>? OnRequestAction;

    /// <summary>
    /// 用户详情事件
    /// </summary>
    public event Action<string>? OnUserDetails;

    /// <summary>
    /// 队伍预览事件
    /// </summary>
    public event Action<PSBattle>? OnTeamPreview;

    /// <summary>
    /// 强制交换事件（参数：对战, 强制交换数组）
    /// </summary>
    public event Action<PSBattle, bool[]>? OnForceSwitch;

    /// <summary>
    /// 选择招式事件
    /// </summary>
    public event Action<PSBattle>? OnChooseMove;

    /// <summary>
    /// 对战结束事件（参数：对战, 是否获胜）
    /// </summary>
    public event Action<PSBattle, bool>? OnBattleEnd;

    /// <summary>
    /// 对战开始事件
    /// </summary>
    public event Action<PSBattle>? OnBattleStart;

    /// <summary>
    /// 对战错误事件（参数：对战, 错误消息）
    /// </summary>
    public event Action<PSBattle, string>? OnBattleError;

    /// <summary>
    /// 对战信息事件（参数：对战, 信息）
    /// </summary>
    public event Action<PSBattle, string>? OnBattleInfo;

    /// <summary>
    /// 对战房间数据事件
    /// </summary>
    public event Action<string>? OnBattleRoomData;

    /// <summary>
    /// 获取房间列表事件
    /// </summary>
    public event Action<RoomList>? OnGetRoomList;

    #endregion

    #region Fields

    /// <summary>
    /// 对战字典
    /// </summary>
    public Dictionary<string, PSBattle> Battles { get; } = new();

    /// <summary>
    /// 日志输出委托
    /// </summary>
    private Action<string>? _writeLog;

    /// <summary>
    /// 挑战ID
    /// </summary>
    private string _challengeId = string.Empty;

    /// <summary>
    /// 挑战字符串
    /// </summary>
    private string _challenge = string.Empty;

    /// <summary>
    /// 用户名
    /// </summary>
    public string UserName { get; }

    /// <summary>
    /// 密码
    /// </summary>
    public string Password { get; }

    /// <summary>
    /// HTTP客户端
    /// </summary>
    private readonly HttpClient _httpClient = new();

    /// <summary>
    /// WebSocket客户端
    /// </summary>
    private ClientWebSocket _webSocket = new();

    /// <summary>
    /// 是否已释放
    /// </summary>
    private bool _disposed = false;

    /// <summary>
    /// PS服务器WebSocket地址
    /// </summary>
    private readonly string _psServerUrl;

    /// <summary>
    /// 登录地址
    /// </summary>
    private readonly string _loginUrl = "https://play.pokemonshowdown.com/~~showdown/action.php";

    #endregion

    #region Constructor

    /// <summary>
    /// 构造函数
    /// </summary>
    /// <param name="userName">用户名</param>
    /// <param name="password">密码</param>
    /// <param name="wsUrl">WebSocket服务器地址</param>
    public SDClient(string userName, string password, string wsUrl = "wss://sim3.psim.us/showdown/websocket")
    {
        UserName = userName;
        Password = password;
        _psServerUrl = wsUrl;
    }

    #endregion

    #region Connection Methods

    /// <summary>
    /// 连接到PS服务器
    /// </summary>
    public async Task ConnectAsync()
    {
        try
        {
            if (!Uri.TryCreate(_psServerUrl.Trim(), UriKind.Absolute, out Uri? webSocketUri))
            {
                throw new ArgumentException($"Invalid WebSocket URI: {_psServerUrl}");
            }

            _webSocket = new ClientWebSocket();
            await _webSocket.ConnectAsync(webSocketUri, CancellationToken.None);
            
            // 开始接收消息
            _ = Task.Run(ReceiveMessages);
            
            await WriteLogAsync("Connected to Pokemon Showdown server", MessageType.Receive);
        }
        catch (Exception ex)
        {
            await WriteLogAsync($"Connection failed: {ex.Message}", MessageType.Receive);
            throw;
        }
    }

    /// <summary>
    /// 断开连接
    /// </summary>
    public async Task DisconnectAsync()
    {
        try
        {
            if (_webSocket.State == WebSocketState.Open)
            {
                await _webSocket.CloseAsync(WebSocketCloseStatus.NormalClosure, "Disconnecting", CancellationToken.None);
            }
        }
        catch (Exception ex)
        {
            await WriteLogAsync($"Disconnect error: {ex.Message}", MessageType.Receive);
        }
        finally
        {
            _webSocket?.Dispose();
        }
    }

    #endregion

    #region Message Handling

    /// <summary>
    /// 接收消息循环
    /// </summary>
    private async Task ReceiveMessages()
    {
        var buffer = new byte[1024 * 16];
        
        while (!_disposed && _webSocket.State == WebSocketState.Open)
        {
            try
            {
                var result = await _webSocket.ReceiveAsync(new ArraySegment<byte>(buffer), CancellationToken.None);
                
                if (result.MessageType == WebSocketMessageType.Text)
                {
                    var message = Encoding.UTF8.GetString(buffer, 0, result.Count);
                    await ProcessReceivedMessage(message);
                }
                else if (result.MessageType == WebSocketMessageType.Close)
                {
                    await WriteLogAsync("WebSocket connection closed by server", MessageType.Receive);
                    break;
                }
            }
            catch (WebSocketException ex)
            {
                await WriteLogAsync($"WebSocket error: {ex.Message}", MessageType.Receive);
                break;
            }
            catch (Exception ex)
            {
                await WriteLogAsync($"Message receiving error: {ex.Message}", MessageType.Receive);
            }
        }
    }

    /// <summary>
    /// 处理接收到的消息
    /// </summary>
    /// <param name="message">消息内容</param>
    private async Task ProcessReceivedMessage(string message)
    {
        await WriteLogAsync(message, MessageType.Receive);
        
        // 根据消息类型进行处理
        var lines = message.Split('\n', StringSplitOptions.RemoveEmptyEntries);
        
        foreach (var line in lines)
        {
            if (line.StartsWith('>'))
            {
                // 房间消息
                await ProcessRoomMessage(line);
            }
            else
            {
                // 全局消息
                await ProcessGlobalMessage(line);
            }
        }
    }

    /// <summary>
    /// 处理房间消息
    /// </summary>
    /// <param name="message">消息内容</param>
    private async Task ProcessRoomMessage(string message)
    {
        // 解析房间ID和消息内容
        var parts = message.Split('|', 2);
        if (parts.Length < 2) return;

        var roomId = parts[0][1..]; // 移除 '>'
        var content = parts[1];

        // 如果是对战房间，处理对战消息
        if (Battles.TryGetValue(roomId, out var battle))
        {
            await ProcessBattleMessage(battle, content);
        }
    }

    /// <summary>
    /// 处理全局消息
    /// </summary>
    /// <param name="message">消息内容</param>
    private async Task ProcessGlobalMessage(string message)
    {
        var parts = message.Split('|');
        if (parts.Length == 0) return;

        var command = parts[0];

        switch (command)
        {
            case "challstr":
                await ProcessChallStr(parts);
                break;
            case "updateuser":
                await ProcessUpdateUser(parts);
                break;
            case "pm":
                await ProcessPrivateMessage(parts);
                break;
            case "updatechallenges":
                await ProcessUpdateChallenges(parts);
                break;
            case "popup":
                await ProcessPopup(parts);
                break;
            default:
                // 其他全局消息的处理
                break;
        }
    }

    /// <summary>
    /// 处理对战消息
    /// </summary>
    /// <param name="battle">对战实例</param>
    /// <param name="content">消息内容</param>
    private async Task ProcessBattleMessage(PSBattle battle, string content)
    {
        var lines = content.Split('|');
        if (lines.Length == 0) return;

        var command = lines[0];

        switch (command)
        {
            case "request":
                if (lines.Length > 1)
                {
                    await battle.RefreshByRequestAsync(lines[1]);
                    OnRequestAction?.Invoke(battle);
                }
                break;
            case "turn":
                if (lines.Length > 1 && int.TryParse(lines[1], out var turn))
                {
                    battle.Turn = turn;
                }
                break;
            case "win":
                if (lines.Length > 1)
                {
                    var winner = lines[1];
                    var isPlayerWin = (battle.PlayerPosition == PlayerPosition.Player1 && winner == battle.Player1Name) ||
                                    (battle.PlayerPosition == PlayerPosition.Player2 && winner == battle.Player2Name);
                    OnBattleEnd?.Invoke(battle, isPlayerWin);
                }
                break;
            case "error":
                if (lines.Length > 1)
                {
                    OnBattleError?.Invoke(battle, lines[1]);
                }
                break;
            default:
                // 其他对战消息的处理 // 可能需要暂存每一回合的事情
                battle.ParseLog(command, lines[1..]);
                break;
        }
    }

    #endregion

    #region Utility Methods

    /// <summary>
    /// 设置日志输出
    /// </summary>
    /// <param name="logAction">日志输出委托</param>
    /// <returns>返回自身以支持链式调用</returns>
    public SDClient LogTo(Action<string> logAction)
    {
        _writeLog = logAction;
        return this;
    }

    /// <summary>
    /// 写入日志
    /// </summary>
    /// <param name="message">消息内容</param>
    /// <param name="messageType">消息类型</param>
    private async Task WriteLogAsync(string message, MessageType messageType)
    {
        var prefix = messageType == MessageType.Send ? "[SEND]" : "[RECV]";
        var logMessage = $"{DateTime.Now:HH:mm:ss} {prefix} {message}";
        
        _writeLog?.Invoke(logMessage);
    }

    #endregion

    #region Message Processing Methods

    private async Task ProcessChallStr(string[] parts)
    {
        if (parts.Length >= 3)
        {
            _challengeId = parts[1];
            _challenge = parts[2];
        }
    }

    private async Task ProcessUpdateUser(string[] parts)
    {
        OnUserUpdate?.Invoke();
    }

    private async Task ProcessPrivateMessage(string[] parts)
    {
        if (parts.Length >= 4)
        {
            var sender = parts[1];
            var message = parts[3];
            OnChat?.Invoke(sender, message);
        }
    }

    private async Task ProcessUpdateChallenges(string[] parts)
    {
        if (parts.Length >= 2)
        {
            try
            {
                var challengesData = JsonSerializer.Deserialize<JsonElement>(parts[1]);
                // 处理挑战数据
            }
            catch (JsonException)
            {
                // JSON解析失败，忽略
            }
        }
    }

    private async Task ProcessPopup(string[] parts)
    {
        if (parts.Length >= 2)
        {
            await WriteLogAsync($"Popup: {parts[1]}", MessageType.Receive);
        }
    }

    #endregion

    #region IDisposable Implementation

    /// <summary>
    /// 释放资源
    /// </summary>
    public void Dispose()
    {
        Dispose(true);
        GC.SuppressFinalize(this);
    }

    /// <summary>
    /// 释放资源的具体实现
    /// </summary>
    /// <param name="disposing">是否为主动释放</param>
    protected virtual void Dispose(bool disposing)
    {
        if (!_disposed && disposing)
        {
            _disposed = true;
            _webSocket?.Dispose();
            _httpClient?.Dispose();
        }
    }

    #endregion
}
