// Generated by Copilot
using System.Net.WebSockets;
using System.Text;
using System.Text.Json;
using PSClient.Core;
using PSClient.Models;

namespace PSClient.Client;

/// <summary>
/// PSClient的WebSocket命令扩展
/// </summary>
public partial class SDClient
{
    #region Basic Commands

    /// <summary>
    /// 发送消息到指定房间
    /// </summary>
    /// <param name="room">房间ID</param>
    /// <param name="messages">消息内容</param>
    public async Task SendAsync(string room, params string[] messages)
    {
        var data = $"{room}|{string.Join('|', messages)}";
        await SendRawMessageAsync(data);
    }

    /// <summary>
    /// 发送原始消息
    /// </summary>
    /// <param name="message">消息内容</param>
    private async Task SendRawMessageAsync(string message)
    {
        try
        {
            if (_webSocket.State == WebSocketState.Open)
            {
                var bytes = Encoding.UTF8.GetBytes(message);
                await _webSocket.SendAsync(
                    new ArraySegment<byte>(bytes),
                    WebSocketMessageType.Text,
                    true,
                    CancellationToken.None);
                
                await WriteLogAsync(message, MessageType.Send);
            }
        }
        catch (Exception ex)
        {
            await WriteLogAsync($"Send error: {ex.Message}", MessageType.Send);
            throw;
        }
    }

    #endregion

    #region Authentication

    /// <summary>
    /// 游客登录
    /// </summary>
    public async Task<bool> LoginAsGuestAsync()
    {
        try
        {
            await SendAsync("", "/trn", UserName);
            return true;
        }
        catch (Exception ex)
        {
            await WriteLogAsync($"Guest login failed: {ex.Message}", MessageType.Send);
            return false;
        }
    }

    /// <summary>
    /// 账号登录
    /// </summary>
    public async Task<bool> LoginAsync()
    {
        return await LoginAsync(UserName, Password, _challengeId, _challenge);
    }

    /// <summary>
    /// 使用指定参数登录
    /// </summary>
    /// <param name="userName">用户名</param>
    /// <param name="password">密码</param>
    /// <param name="challengeId">挑战ID</param>
    /// <param name="challenge">挑战字符串</param>
    public async Task<bool> LoginAsync(string userName, string password, string challengeId, string challenge)
    {
        try
        {
            // 构建登录请求
            var loginData = new FormUrlEncodedContent(new[]
            {
                new KeyValuePair<string, string>("act", "login"),
                new KeyValuePair<string, string>("name", userName),
                new KeyValuePair<string, string>("pass", password),
                new KeyValuePair<string, string>("challstr", $"{challengeId}|{challenge}")
            });

            // 发送登录请求
            var response = await _httpClient.PostAsync(_loginUrl, loginData);
            var responseContent = await response.Content.ReadAsStringAsync();

            // 解析响应
            if (responseContent.StartsWith("]"))
            {
                responseContent = responseContent[1..];
            }

            var loginResult = JsonSerializer.Deserialize<JsonElement>(responseContent);
            
            if (loginResult.TryGetProperty("curuser", out var curUser) &&
                curUser.TryGetProperty("loggedin", out var loggedIn) &&
                loggedIn.GetBoolean())
            {
                // 登录成功，发送用户认证
                if (loginResult.TryGetProperty("assertion", out var assertion))
                {
                    await SendAsync("", "/trn", userName, "0", assertion.GetString() ?? "");
                    return true;
                }
            }

            return false;
        }
        catch (Exception ex)
        {
            await WriteLogAsync($"Login failed: {ex.Message}", MessageType.Send);
            return false;
        }
    }

    #endregion

    #region Battle Commands

    /// <summary>
    /// 搜索对战
    /// </summary>
    /// <param name="format">对战格式</param>
    public async Task SearchBattleAsync(string format)
    {
        await SendAsync("", "/search", format);
    }

    /// <summary>
    /// 取消搜索
    /// </summary>
    public async Task CancelSearchAsync()
    {
        await SendAsync("", "/cancelsearch");
    }

    /// <summary>
    /// 发起挑战
    /// </summary>
    /// <param name="player">目标玩家</param>
    /// <param name="format">对战格式</param>
    public async Task ChallengeAsync(string player, string format)
    {
        await SendAsync("", "/challenge", player, format);
    }

    /// <summary>
    /// 取消挑战
    /// </summary>
    /// <param name="player">目标玩家</param>
    public async Task CancelChallengeAsync(string player)
    {
        await SendAsync("", "/cancelchallenge", player);
    }

    /// <summary>
    /// 接受挑战
    /// </summary>
    /// <param name="player">挑战者</param>
    public async Task AcceptChallengeAsync(string player)
    {
        await SendAsync("", "/accept", player);
    }

    /// <summary>
    /// 拒绝挑战
    /// </summary>
    /// <param name="player">挑战者</param>
    public async Task RejectChallengeAsync(string player)
    {
        await SendAsync("", "/reject", player);
    }

    #endregion

    #region Battle Actions

    /// <summary>
    /// 发送行动指令
    /// </summary>
    /// <param name="battleTag">对战标识</param>
    /// <param name="turn">回合数</param>
    /// <param name="chooseData">选择数据数组</param>
    public async Task SendMoveAsync(string battleTag, int turn, params ChooseData[] chooseData)
    {
        var commands = chooseData.Select(cd => cd.ToCommandString()).ToArray();
        await SendAsync(battleTag, "/choose", string.Join(",", commands), turn.ToString());
    }

    /// <summary>
    /// 发送单个招式
    /// </summary>
    /// <param name="battleTag">对战标识</param>
    /// <param name="moveId">招式ID</param>
    /// <param name="turn">回合数</param>
    public async Task SendMoveAsync(string battleTag, int moveId, int turn)
    {
        await SendMoveAsync(battleTag, turn, new MoveChooseData(moveId));
    }

    /// <summary>
    /// 发送交换指令
    /// </summary>
    /// <param name="battleTag">对战标识</param>
    /// <param name="pokemonId">宝可梦ID</param>
    /// <param name="turn">回合数</param>
    public async Task SendSwitchAsync(string battleTag, int pokemonId, int turn)
    {
        await SendMoveAsync(battleTag, turn, new SwitchData(pokemonId));
    }

    /// <summary>
    /// 发送队伍排序
    /// </summary>
    /// <param name="battleTag">对战标识</param>
    /// <param name="teamOrder">队伍排序</param>
    /// <param name="turn">回合数</param>
    public async Task SendTeamOrderAsync(string battleTag, string teamOrder, int turn)
    {
        await SendAsync(battleTag, "/team", teamOrder);
    }

    /// <summary>
    /// 投降
    /// </summary>
    /// <param name="battleTag">对战标识</param>
    public async Task SendForfeitAsync(string battleTag)
    {
        await SendAsync(battleTag, "/forfeit");
    }

    #endregion

    #region Room Management

    /// <summary>
    /// 加入房间
    /// </summary>
    /// <param name="roomId">房间ID</param>
    public async Task JoinRoomAsync(string roomId)
    {
        await SendAsync("", "/join", roomId);
    }

    /// <summary>
    /// 离开房间
    /// </summary>
    /// <param name="roomId">房间ID</param>
    public async Task SendLeaveAsync(string roomId)
    {
        await SendAsync(roomId, "/leave");
    }

    /// <summary>
    /// 发送房间消息
    /// </summary>
    /// <param name="roomId">房间ID</param>
    /// <param name="message">消息内容</param>
    public async Task SendMessageAsync(string roomId, string message)
    {
        await SendAsync(roomId, message);
    }

    #endregion

    #region User Management

    /// <summary>
    /// 设置头像
    /// </summary>
    /// <param name="avatarId">头像ID</param>
    public async Task SetAvatarAsync(string avatarId)
    {
        await SendAsync("", "/avatar", avatarId);
    }

    /// <summary>
    /// 更改队伍
    /// </summary>
    /// <param name="team">队伍字符串</param>
    public async Task ChangeTeamAsync(string team)
    {
        await SendAsync("", "/utm", team);
    }

    /// <summary>
    /// 获取用户详情
    /// </summary>
    /// <param name="userName">用户名</param>
    public async Task GetUserDetailsAsync(string userName)
    {
        await SendAsync("", "/cmd", "userdetails", userName);
    }

    /// <summary>
    /// 发送私聊消息
    /// </summary>
    /// <param name="userName">目标用户</param>
    /// <param name="message">消息内容</param>
    public async Task SendPrivateMessageAsync(string userName, string message)
    {
        await SendAsync("", "/msg", userName, message);
    }

    #endregion

    #region Information Queries

    /// <summary>
    /// 获取房间列表
    /// </summary>
    /// <param name="format">格式过滤（可选）</param>
    /// <param name="minRating">最低评级过滤（可选）</param>
    public async Task GetRoomListAsync(string? format = null, int minRating = -1)
    {
        var command = "/cmd rooms";
        if (!string.IsNullOrEmpty(format))
        {
            command += $" {format}";
        }
        if (minRating >= 0)
        {
            command += $" {minRating}";
        }
        
        await SendAsync("", command);
    }

    /// <summary>
    /// 获取用户排名信息
    /// </summary>
    /// <param name="userName">用户名</param>
    public async Task<List<RankData>> GetRankAsync(string userName)
    {
        // 这里需要实现获取排名的逻辑
        // 由于PS的API限制，可能需要通过其他方式获取
        return new List<RankData>();
    }

    #endregion
}
