// Generated by Copilot
using PSClient.Client;
using PSClient.Extensions;

namespace PSClient.Examples;

/// <summary>
/// 简单的PS客户端示例程序
/// </summary>
public class SimpleExample
{    /// <summary>
    /// 运行示例
    /// </summary>
    public static async Task RunAsync()
    {
        // 创建客户端实例
        var client = new PSClient.Client.SDClient("example_user", "example_password");
        
        // 设置日志输出
        client.LogTo(Console.WriteLine);
        
        try
        {
            // 连接到服务器
            Console.WriteLine("正在连接到Pokemon Showdown服务器...");
            await client.ConnectAsync();
            
            // 设置事件处理器
            SetupEventHandlers(client);
            
            // 尝试游客登录（更安全的测试方式）
            Console.WriteLine("正在以游客身份登录...");
            var loginSuccess = await client.LoginAsGuestAsync();
            
            if (loginSuccess)
            {
                Console.WriteLine("登录成功！");
                
                // 搜索随机对战
                Console.WriteLine("正在搜索随机对战...");
                await client.SearchBattleAsync("gen9randombattle");
                
                // 保持程序运行
                Console.WriteLine("程序正在运行中，按任意键退出...");
                Console.ReadKey();
            }
            else
            {
                Console.WriteLine("登录失败！");
            }
        }
        catch (Exception ex)
        {
            Console.WriteLine($"发生错误: {ex.Message}");
        }
        finally
        {
            // 清理资源
            Console.WriteLine("正在断开连接...");
            await client.DisconnectAsync();
            client.Dispose();
        }
    }
    
    /// <summary>
    /// 设置事件处理器
    /// </summary>
    /// <param name="client">PS客户端</param>
    private static void SetupEventHandlers(PSClient.Client.SDClient client)
    {
        // 对战开始事件
        client.OnBattleStart += (battle) =>
        {
            Console.WriteLine($"对战开始！房间ID: {battle.RoomTag}");
            Console.WriteLine($"玩家位置: {battle.PlayerPosition}");
        };
        
        // 需要选择行动时
        client.OnRequestAction += async (battle) =>
        {
            Console.WriteLine($"回合 {battle.Turn}: 需要选择行动");
            
            try
            {
                // 简单的AI策略：优先使用招式，如果不能使用则尝试交换
                if (battle.CanUseMove(1))
                {
                    Console.WriteLine("使用第一个招式");
                    await battle.SendMoveAsync(PSClientExtensions.Move(1));
                }
                else if (battle.CanUseMove(2))
                {
                    Console.WriteLine("使用第二个招式");
                    await battle.SendMoveAsync(PSClientExtensions.Move(2));
                }
                else
                {
                    // 尝试交换宝可梦
                    for (int i = 2; i <= 6; i++)
                    {
                        if (battle.CanSwitchTo(i))
                        {
                            Console.WriteLine($"交换到宝可梦 {i}");
                            await battle.SendMoveAsync(PSClientExtensions.Switch(i));
                            break;
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine($"发送行动时出错: {ex.Message}");
            }
        };
        
        // 队伍预览事件
        client.OnTeamPreview += async (battle) =>
        {
            Console.WriteLine("队伍预览阶段");
            
            try
            {
                // 发送默认的队伍排序
                await battle.SendTeamOrderAsync("1,2,3,4,5,6");
            }
            catch (Exception ex)
            {
                Console.WriteLine($"发送队伍排序时出错: {ex.Message}");
            }
        };
        
        // 对战结束事件
        client.OnBattleEnd += (battle, isWin) =>
        {
            Console.WriteLine($"对战结束！结果: {(isWin ? "胜利" : "失败")}");
            
            // 获取对战统计
            var stats = battle.GetBattleStats();
            Console.WriteLine($"对战统计:");
            Console.WriteLine($"  - 总回合数: {stats.Turn}");
            Console.WriteLine($"  - 我方存活宝可梦: {stats.MyAlivePokemonCount}");
            Console.WriteLine($"  - 对手存活宝可梦: {stats.OpponentAlivePokemonCount}");
            Console.WriteLine($"  - 优势度: {stats.AdvantageRatio:F2}");
        };
        
        // 对战错误事件
        client.OnBattleError += (battle, error) =>
        {
            Console.WriteLine($"对战错误 [{battle.RoomTag}]: {error}");
        };
        
        // 聊天消息事件
        client.OnChat += (user, message) =>
        {
            Console.WriteLine($"[聊天] {user}: {message}");
        };
        
        // 用户信息更新事件
        client.OnUserUpdate += () =>
        {
            Console.WriteLine("用户信息已更新");
        };
    }
}

/// <summary>
/// 程序入口点
/// </summary>
public class Program
{
    public static async Task Main(string[] args)
    {
        Console.WriteLine("=== PSClient 示例程序 ===");
        Console.WriteLine("这个程序演示了如何使用重构后的PSClient库");
        Console.WriteLine();
        
        await SimpleExample.RunAsync();
    }
}
