// Generated by Copilot
namespace PSClient.Core;

/// <summary>
/// 选择数据基类
/// </summary>
public abstract class ChooseData
{
    /// <summary>
    /// 是否跳过
    /// </summary>
    public bool IsPass { get; set; } = false;
    
    /// <summary>
    /// 转换为PS指令字符串
    /// </summary>
    public abstract string ToCommandString();
}
