// Generated by Copilot
namespace PSClient.Core;

/// <summary>
/// 招式选择数据类
/// </summary>
public class MoveChooseData : ChooseData
{
    /// <summary>
    /// 招式ID
    /// </summary>
    public int MoveId { get; set; } = 0;
    
    /// <summary>
    /// 目标位置（999表示默认目标）
    /// </summary>
    public int Target { get; set; } = 999;
    
    /// <summary>
    /// 是否极巨化
    /// </summary>
    public bool IsDynamax { get; set; } = false;

    /// <summary>
    /// 构造函数
    /// </summary>
    /// <param name="moveId">招式ID</param>
    /// <param name="target">目标位置</param>
    /// <param name="isDynamax">是否极巨化</param>
    public MoveChooseData(int moveId, int target = 999, bool isDynamax = false)
    {
        MoveId = moveId;
        Target = target;
        IsDynamax = isDynamax;
    }

    /// <summary>
    /// 转换为PS指令字符串
    /// </summary>
    public override string ToCommandString()
    {
        if (IsPass)
        {
            return "pass";
        }

        var command = $"move {MoveId}";
        
        if (Target != 999)
        {
            command += $" {Target}";
        }
        
        if (IsDynamax)
        {
            command += " dynamax";
        }

        return command;
    }

    public override string ToString() => ToCommandString();
}
