// Generated by Copilot
namespace PSClient.Core;

/// <summary>
/// 交换宝可梦选择数据类
/// </summary>
public class SwitchData : ChooseData
{
    /// <summary>
    /// 要换上来的宝可梦在队伍里的位置
    /// </summary>
    public int PokemonId { get; set; }

    /// <summary>
    /// 构造函数
    /// </summary>
    /// <param name="pokemonId">宝可梦ID</param>
    public SwitchData(int pokemonId)
    {
        PokemonId = pokemonId;
    }

    /// <summary>
    /// 转换为PS指令字符串
    /// </summary>
    public override string ToCommandString()
    {
        if (IsPass) 
            return "pass";
            
        return $"switch {PokemonId}";
    }

    public override string ToString() => ToCommandString();
}
