// Generated by Copilot
using PSClient.Battle;
using PSClient.Client;
using PSClient.Core;
using PSClient.Models;

namespace PSClient.Extensions;

/// <summary>
/// PSClient扩展方法
/// </summary>
public static class PSClientExtensions
{
    /// <summary>
    /// 快速创建招式选择数据
    /// </summary>
    /// <param name="moveId">招式ID</param>
    /// <param name="target">目标</param>
    /// <param name="isDynamax">是否极巨化</param>
    /// <returns>招式选择数据</returns>
    public static MoveChooseData Move(int moveId, int target = 999, bool isDynamax = false)
    {
        return new MoveChooseData(moveId, target, isDynamax);
    }

    /// <summary>
    /// 快速创建交换选择数据
    /// </summary>
    /// <param name="pokemonId">宝可梦ID</param>
    /// <returns>交换选择数据</returns>
    public static SwitchData Switch(int pokemonId)
    {
        return new SwitchData(pokemonId);
    }

    /// <summary>
    /// 快速创建跳过选择数据
    /// </summary>
    /// <returns>跳过选择数据</returns>
    public static MoveChooseData Pass()
    {
        return new MoveChooseData(0) { IsPass = true };
    }
}

/// <summary>
/// PSBattle扩展方法
/// </summary>
public static class PSBattleExtensions
{
    /// <summary>
    /// 获取我方第一只场上宝可梦
    /// </summary>
    /// <param name="battle">对战实例</param>
    /// <returns>宝可梦实例或null</returns>
    public static PSBattlePokemon? GetMyActivePokemon(this PSBattle battle)
    {
        return battle.MySide.FirstOrDefault(p => p != null && p.IsActive);
    }

    /// <summary>
    /// 获取对手第一只场上宝可梦
    /// </summary>
    /// <param name="battle">对战实例</param>
    /// <returns>宝可梦实例或null</returns>
    public static PSBattlePokemon? GetOpponentActivePokemon(this PSBattle battle)
    {
        return battle.OpponentSide.FirstOrDefault(p => p != null && p.IsActive);
    }

    /// <summary>
    /// 获取所有我方存活的宝可梦
    /// </summary>
    /// <param name="battle">对战实例</param>
    /// <returns>存活的宝可梦列表</returns>
    public static IEnumerable<PSBattlePokemon> GetMyAlivePokemon(this PSBattle battle)
    {
        return battle.MyTeam.Where(p => p != null && !p.IsFainted);
    }

    /// <summary>
    /// 获取所有对手存活的宝可梦
    /// </summary>
    /// <param name="battle">对战实例</param>
    /// <returns>存活的宝可梦列表</returns>
    public static IEnumerable<PSBattlePokemon> GetOpponentAlivePokemon(this PSBattle battle)
    {
        return battle.OpponentTeam.Where(p => p != null && !p.IsFainted);
    }

    /// <summary>
    /// 检查是否可以使用招式
    /// </summary>
    /// <param name="battle">对战实例</param>
    /// <param name="moveId">招式ID</param>
    /// <returns>是否可以使用</returns>
    public static bool CanUseMove(this PSBattle battle, int moveId)
    {
        var activePokemon = battle.GetMyActivePokemon();
        if (activePokemon == null || activePokemon.IsFainted)
            return false;

        // 这里可以添加更多的招式使用条件检查
        // 比如PP、禁用状态等
        return moveId >= 1 && moveId <= 4;
    }

    /// <summary>
    /// 检查是否可以交换宝可梦
    /// </summary>
    /// <param name="battle">对战实例</param>
    /// <param name="pokemonId">宝可梦ID</param>
    /// <returns>是否可以交换</returns>
    public static bool CanSwitchTo(this PSBattle battle, int pokemonId)
    {
        if (pokemonId < 1 || pokemonId > 6)
            return false;

        var targetPokemon = battle.MyTeam.ElementAtOrDefault(pokemonId - 1);
        if (targetPokemon == null || targetPokemon.IsFainted || targetPokemon.IsActive)
            return false;

        var activePokemon = battle.GetMyActivePokemon();
        if (activePokemon?.IsTrapped == true)
            return false;

        return true;
    }

    /// <summary>
    /// 获取对战统计信息
    /// </summary>
    /// <param name="battle">对战实例</param>
    /// <returns>对战统计</returns>
    public static BattleStats GetBattleStats(this PSBattle battle)
    {
        var myAlive = battle.GetMyAlivePokemon().Count();
        var opponentAlive = battle.GetOpponentAlivePokemon().Count();
        
        var myTotalHP = battle.GetMyAlivePokemon().Sum(p => p.HPPercentage);
        var opponentTotalHP = battle.GetOpponentAlivePokemon().Sum(p => p.HPPercentage);

        return new BattleStats
        {
            MyAlivePokemonCount = myAlive,
            OpponentAlivePokemonCount = opponentAlive,
            MyTotalHPPercentage = myTotalHP,
            OpponentTotalHPPercentage = opponentTotalHP,
            Turn = battle.Turn
        };
    }
}

/// <summary>
/// 对战统计信息
/// </summary>
public class BattleStats
{
    /// <summary>
    /// 我方存活宝可梦数量
    /// </summary>
    public int MyAlivePokemonCount { get; set; }

    /// <summary>
    /// 对手存活宝可梦数量
    /// </summary>
    public int OpponentAlivePokemonCount { get; set; }

    /// <summary>
    /// 我方总HP百分比
    /// </summary>
    public double MyTotalHPPercentage { get; set; }

    /// <summary>
    /// 对手总HP百分比
    /// </summary>
    public double OpponentTotalHPPercentage { get; set; }

    /// <summary>
    /// 当前回合数
    /// </summary>
    public int Turn { get; set; }

    /// <summary>
    /// 我方优势度（-1到1，负数表示劣势）
    /// </summary>
    public double AdvantageRatio
    {
        get
        {
            var totalOpponent = OpponentAlivePokemonCount * 100 + OpponentTotalHPPercentage;
            var totalMy = MyAlivePokemonCount * 100 + MyTotalHPPercentage;
            var total = totalMy + totalOpponent;
            
            if (total == 0) return 0;
            
            return (totalMy - totalOpponent) / total;
        }
    }
}
