// Generated by Copilot
namespace PSClient.Utilities;

/// <summary>
/// PS相关工具类
/// </summary>
public static class PSTools
{
    /// <summary>
    /// 清理宝可梦名称中的特殊字符
    /// </summary>
    /// <param name="name">原始名称</param>
    /// <returns>清理后的名称</returns>
    public static string CleanPokemonName(string name)
    {
        if (string.IsNullOrEmpty(name))
            return string.Empty;

        return name.Replace("-*", "")
                  .Replace("♀", "-f")
                  .Replace("♂", "-m")
                  .Trim();
    }

    /// <summary>
    /// 解析宝可梦位置信息
    /// </summary>
    /// <param name="position">位置字符串（如 "p1a", "p2b"）</param>
    /// <returns>元组：(玩家位置, 场上位置)</returns>
    public static (PlayerPosition player, int slot) ParsePosition(string position)
    {
        if (string.IsNullOrEmpty(position) || position.Length < 3)
            return (PlayerPosition.Player1, 0);

        var playerPos = position[1] == '1' ? PlayerPosition.Player1 : PlayerPosition.Player2;
        var slot = position[2] switch
        {
            'a' => 0,
            'b' => 1,
            'c' => 2,
            'd' => 3,
            _ => 0
        };

        return (playerPos, slot);
    }

    /// <summary>
    /// 解析HP信息
    /// </summary>
    /// <param name="hpString">HP字符串（如 "100/100", "50/100 par"）</param>
    /// <returns>元组：(当前HP, 最大HP, 状态)</returns>
    public static (int current, int max, string status) ParseHP(string hpString)
    {
        if (string.IsNullOrEmpty(hpString))
            return (0, 0, string.Empty);

        var parts = hpString.Split(' ');
        var hpPart = parts[0];
        var status = parts.Length > 1 ? parts[1] : string.Empty;

        var hpValues = hpPart.Split('/');
        if (hpValues.Length == 2 && 
            int.TryParse(hpValues[0], out var current) && 
            int.TryParse(hpValues[1], out var max))
        {
            return (current, max, status);
        }

        return (0, 0, status);
    }

    /// <summary>
    /// 解析百分比HP
    /// </summary>
    /// <param name="hpString">HP字符串（如 "50%", "100%"）</param>
    /// <returns>HP百分比（0-100）</returns>
    public static double ParseHPPercentage(string hpString)
    {
        if (string.IsNullOrEmpty(hpString))
            return 0;

        var cleanString = hpString.Replace("%", "").Trim();
        if (double.TryParse(cleanString, out var percentage))
        {
            return Math.Max(0, Math.Min(100, percentage));
        }

        return 0;
    }

    /// <summary>
    /// 格式化队伍字符串
    /// </summary>
    /// <param name="team">队伍对象</param>
    /// <returns>PS格式的队伍字符串</returns>
    public static string FormatTeam(object team)
    {
        // 这里需要根据实际的队伍对象结构来实现
        // 暂时返回空字符串
        return string.Empty;
    }

    /// <summary>
    /// 验证对战格式
    /// </summary>
    /// <param name="format">格式字符串</param>
    /// <returns>是否为有效格式</returns>
    public static bool IsValidFormat(string format)
    {
        if (string.IsNullOrEmpty(format))
            return false;

        var validFormats = new[]
        {
            "gen9ou", "gen9uu", "gen9ru", "gen9nu", "gen9pu",
            "gen9doubles", "gen9vgc2024", "gen9battlestadiumsingles",
            "gen8ou", "gen7ou", "gen6ou", "gen5ou", "gen4ou", "gen3ou",
            "gen9randombattle", "gen9hackmons", "gen9almostanyability"
        };

        return validFormats.Contains(format.ToLowerInvariant());
    }

    /// <summary>
    /// 生成随机房间ID
    /// </summary>
    /// <returns>随机房间ID</returns>
    public static string GenerateRoomId()
    {
        var random = new Random();
        const string chars = "abcdefghijklmnopqrstuvwxyz0123456789";
        return new string(Enumerable.Repeat(chars, 8)
                                  .Select(s => s[random.Next(s.Length)])
                                  .ToArray());
    }

    /// <summary>
    /// 解析回合数
    /// </summary>
    /// <param name="turnString">回合字符串</param>
    /// <returns>回合数</returns>
    public static int ParseTurn(string turnString)
    {
        if (string.IsNullOrEmpty(turnString))
            return 0;

        if (int.TryParse(turnString, out var turn))
        {
            return Math.Max(0, turn);
        }

        return 0;
    }

    /// <summary>
    /// 检查是否为有效的宝可梦名称
    /// </summary>
    /// <param name="name">名称</param>
    /// <returns>是否有效</returns>
    public static bool IsValidPokemonName(string name)
    {
        if (string.IsNullOrWhiteSpace(name))
            return false;

        // 基本的名称验证规则
        return name.Length <= 20 && 
               !name.Contains('|') && 
               !name.Contains('\n') &&
               !name.Contains('\r');
    }

    /// <summary>
    /// 格式化时间戳
    /// </summary>
    /// <param name="timestamp">时间戳</param>
    /// <returns>格式化的时间字符串</returns>
    public static string FormatTimestamp(DateTime timestamp)
    {
        return timestamp.ToString("yyyy-MM-dd HH:mm:ss");
    }

    /// <summary>
    /// 解析对战结果
    /// </summary>
    /// <param name="winner">获胜者名称</param>
    /// <param name="player1">玩家1名称</param>
    /// <param name="player2">玩家2名称</param>
    /// <returns>对战结果</returns>
    public static BattleResult ParseBattleResult(string winner, string player1, string player2)
    {
        if (string.IsNullOrEmpty(winner))
            return BattleResult.Draw;

        if (winner.Equals(player1, StringComparison.OrdinalIgnoreCase))
            return BattleResult.Player1Win;
        
        if (winner.Equals(player2, StringComparison.OrdinalIgnoreCase))
            return BattleResult.Player2Win;

        return BattleResult.Draw;
    }
}
