using System.Net.WebSockets;
using Serilog;
using System.Text;
using System.Text.Json;

namespace Showdown;
// Generated by Copilot
public enum MsgType
{
    Receive,
    Send
}
public enum Usage
{
    Standby = 0,
    ChallOwner = 1,
    Search = 2,
}


public record ClientInfo(
    string Name, 
    string Password,
     string Server = "sim.smogon.com:8000",
     string AuthSUrl = "https://play.pokemonshowdown.com/~~showdown/action.php",
     bool UseSSL = true

 )
{
    public static ClientInfo CreateAnonymous(string name, string server = "sim.smogon.com:8000")
    {
        return new ClientInfo(name, string.Empty, server);
    }

    public static ClientInfo Create(string name, string password, string server = "sim.smogon.com:8000")
    {
        return new ClientInfo(name, password, server);
    }
}
public record ChallInfo(string ChallId, string ChallStr)
{
    public static ChallInfo Create(string challId, string challStr)
    {
        return new ChallInfo(challId, challStr);
    }
}

public partial class ShowdownClient
{

    public Dictionary<string, PSBattle> Battles = new();

    private Action<string> WriteLog;
    public Action UpdateUser;
    /// <summary>
    /// 参数为playerid和规则
    /// </summary>
    public event Action<PSBattle> OnSetTeam;
    public event Action<string, string> OnChallenge;
    /// <summary>
    /// 参数为playerid和信息
    /// </summary>
    public Action<string, string> OnChat;
    public event Action<PSBattle> RequestsAction;
    //public Action<string, string> RequestsAction;
    public Action<string> OnUserDetails;

    public event Action<Roomlist>? OnGetRoomList;
    /// <summary>
    /// 参数为对战和是否赢了
    /// </summary>
    public event Action<PSBattle, bool> OnBattleEnd;
    public event Action<PSBattle> OnBattleStart;
    public event Action<PSBattle, string> OnBattleError;

    public event Action<PSBattle, string> BattleInfo;
    public event Action<string> OnBattleRuleInit;

    public ChallInfo? ChallInfo { get; private set; } = null;


    // Generated by Copilot
    private static readonly ILogger Logger = Log.ForContext<ShowdownClient>();

    public ShowdownClient(ClientInfo clientInfo)
    {
        ClientInfo = clientInfo;

        // Generated by Copilot - 初始化Serilog配置
        if (!Log.Logger.GetType().Name.Contains("SilentLogger"))
        {
            return; // 已经配置过了
        }

        Log.Logger = new LoggerConfiguration()
            .MinimumLevel.Debug()
            .WriteTo.Console()
            .WriteTo.File("logs/showdown-client-.txt", rollingInterval: RollingInterval.Day)
            .CreateLogger();
    }

    public ClientInfo ClientInfo { get; }
    private HttpClient? _httpClient = new();
    private ClientWebSocket? _webSocket = new();
    private bool _disposed = false;
    Thread? _recvThread = null;

    //public async Task<bool> ConnectSSLAsync()
    //{
    //    var uri = new Uri($"wss://{ClientInfo.Server}/showdown/websocket");
    //    await _webSocket.ConnectAsync(uri, CancellationToken.None);
    //    _recvThread = new Thread(async () => await RecvAsync());
    //    _recvThread.Start();
    //    return _webSocket.State == WebSocketState.Open;
        
    //}
    public async Task<bool> ConnectAsync()
    {
        var uri = new Uri($"{(ClientInfo.UseSSL?"wss":"ws")}://{ClientInfo.Server}/showdown/websocket");
        await _webSocket.ConnectAsync(uri, CancellationToken.None);
        _recvThread = new Thread(async () => await RecvAsync());
        _recvThread.Start();
        return _webSocket.State == WebSocketState.Open;
    }
    private async Task RecvAsync()
    {
        var buffer = new byte[1024 * 32]; // 32KB buffer
        while (_webSocket.State == WebSocketState.Open
        && !_disposed
        )
        {
            try
            {
                // Generated by Copilot - 使用Serilog记录接收线程状态
                Logger.Information("Receiving messages from WebSocket...");
                var result = await _webSocket.ReceiveAsync(new ArraySegment<byte>(buffer), CancellationToken.None);
                if (result.MessageType == WebSocketMessageType.Close)
                {
                    await _webSocket.CloseAsync(WebSocketCloseStatus.NormalClosure, "Closing", CancellationToken.None);
                }
                else if (result.MessageType == WebSocketMessageType.Text)
                {
                    var message = Encoding.UTF8.GetString(buffer, 0, result.Count);
                    // Generated by Copilot - 使用Serilog记录接收到的消息
                    WriteLogAsync(message, MsgType.Receive);
                    await ExcuteMessageAsync(message);
                }
                else
                {
                    Logger.Warning("Received unsupported message type: {MessageType}", result.MessageType);
                }
            }
            catch (Exception ex)
            {
                Logger.Error(ex, "Error in receiving thread");
                break;
            }

        }
    }
    public async Task<bool> LoginAsync(string userName, string challId, string chall)
    {

        var content = new FormUrlEncodedContent(
      [
              new KeyValuePair<string, string>("act", "getassertion"),
                new KeyValuePair<string, string>("userid", userName),
                new KeyValuePair<string, string>("challstr", $"{challId}%7C{chall}")
          ]);
        var response = await _httpClient.PostAsync(ClientInfo.AuthSUrl, content);

        var dd = await response.Content.ReadAsStringAsync();

        await SendAsync("", $"/trn {userName},0,{dd}");
        await SetAvatarAsync("lillie");
        return true;
    }


    public async Task<bool> LoginAsync(string userName, string password, string challId, string chall)
    {

        var content = new FormUrlEncodedContent(
            [
                    new KeyValuePair<string, string>("act", "login"),
                new KeyValuePair<string, string>("name", userName),
                new KeyValuePair<string, string>("pass", password),
                new KeyValuePair<string, string>("challstr", $"{challId}%7C{chall}")
                ]);

        // 发送登录请求
        var response = await _httpClient.PostAsync(ClientInfo.AuthSUrl, content);
        var responseString = await response.Content.ReadAsStringAsync();
        var json = responseString[1..]; // 跳过第一个字符
        var data = JsonDocument.Parse(json).RootElement;

        if (!data.GetProperty("curuser").GetProperty("loggedin").GetBoolean())
            return false;

        var assertion = data.GetProperty("assertion").GetString();
        await SendAsync("", $"/trn {userName},0,{assertion}");
        await SetAvatarAsync("lillie");
        return true;
    }

    public async Task<bool> LoginAsync()
    {
        // Generated by Copilot
        // 优化后的登录流程
        // Generated by Copilot
        // 优化后的登录流程


        while ( ChallInfo == null)
        {
            await Task.Delay(500); // 这里加个超时
        }

        var userName = ClientInfo.Name;
        var password = ClientInfo.Password;
        var challId = ChallInfo.ChallId; // TODO: 获取challId
        var chall = ChallInfo.ChallStr;   // TODO: 获取chall

        if (string.IsNullOrEmpty(password))
        {
            return await LoginAsync(userName, challId, chall);
        }
        else
        {
            return await LoginAsync(userName, password, challId, chall);

        }

        // 构建请求内容
        // Generated by Copilot
    }

    public void Disconnect()
    {
        if (_webSocket != null && _webSocket.State == WebSocketState.Open)
        {
            _webSocket.CloseAsync(WebSocketCloseStatus.NormalClosure, "Client disconnected", CancellationToken.None).Wait();
        }
        _disposed = true;
        _recvThread?.Join();
        _recvThread = null;
        _webSocket?.Dispose();
        _webSocket = null;
        Logger.Information("Disconnected from WebSocket");
    }

    // Generated by Copilot - 使用Serilog记录日志
    private void WriteLogAsync(string msg, MsgType type)
    {
        switch (type)
        {
            case MsgType.Receive:
                Logger.Information("Received: {Message}", msg);
                break;
            case MsgType.Send:
                Logger.Information("Sent: {Message}", msg);
                break;
            default:
                Logger.Warning("Unknown message type: {MessageType}, Message: {Message}", type, msg);
                break;
        }
    }


    private async Task BattleTagAsync(string msg, Usage usage = Usage.Standby)
    {
        string[] battleData = msg.Split('\n');
        string tag = battleData[0].Split('|')[0][1..];
        // Console.WriteLine($"tag: {tag}");
        var battle = Battles.GetValueOrDefault(tag) ?? new PSBattle(this, tag);
        BattleInfo?.Invoke(battle, msg);

        for (int i = 1; i < battleData.Length; i++)
        {
            string[] currData = battleData[i].Split('|');
            if (currData.Length < 2) continue;
            string cmd = currData[1];
            string[] other = currData[2..];

            //Console.WriteLine(cmd);
            //Console.WriteLine(battle.BattleData.GetMyTeam());
            battle.BattleData = (await battle.BattleData.ApplyLog(cmd, other)).AddTurnLog(battleData[i]);
            //Console.WriteLine(cmd);
            //Console.WriteLine(battle.BattleData.GetMyTeam());
            switch (cmd)
            {
                case "init":
                    Battles.TryAdd(tag, battle);
                    OnBattleStart?.Invoke(battle);
                    break;
                case "player":
                    // Todo: 这个也要高的battledata里
                    if (other[1] == ClientInfo.Name)
                    {
                        battle.PlayerPosition = other[0] == "p1" ? PlayerPosition.Player1 : PlayerPosition.Player2;
                        // Console.WriteLine("玩家位置: " + battle.PlayerPos);
                        if (battle.PlayerPosition == PlayerPosition.Player1)
                        {
                            battle.Player1 = ClientInfo.Name;
                        }
                        else
                        {
                            // battle.Turn++;
                            battle.Player2 = ClientInfo.Name;
                        }
                    }
                    else
                    {
                        if (other[0] == "p1")
                        {
                            battle.Player1 = other[1];
                        }
                        else
                        {
                            battle.Player2 = other[1];
                        }
                    }
                    break;
                case "request":
                    if (other[0] != "")
                    {
                        RequestsAction?.Invoke(battle);

                        // battle.Turn += 2;

                        //if (JsonDocument.Parse(other[0]).RootElement.TryGetProperty("forceSwitch", out var c))
                        //{
                        //    await SendSwitchAsync(tag, ++battle.idx, battle.Turn);
                        //}
                        // 随机队伍信息
                        // 应该还需要拆分
                        if (other[0].Length == 1)
                        {
                            await battle.RefreshByRequestAsync(other[1].Split('\n')[1]);
                            // RequestsAction?.Invoke(tag, other[1].Split('\n')[1]);
                            // other[1].split('\n')[1] 为队伍信息
                        }
                        else
                        {
                            await battle.RefreshByRequestAsync(other[0]);
                            // RequestsAction?.Invoke(tag, other[0]);

                            // other[0] 为队伍信息
                        }
                    }

                    break;
                case "teampreview":
                    // 后面还有个
                    OnSetTeam?.Invoke(battle);

                    //OnTeampreview?.Invoke(battle);
                    // 选择队伍
                    // 可能需要事件通知
                    // MakeOrder
                    break;
                case "turn":
                    // 回合开始
                    // 做出操作
                    // MakeAction
                    // Console.WriteLine("到了turn");
                    //OnChooseMove?.Invoke(battle);
                    // await SendMoveAsync(tag, 1, battle.Turn);
                    battle.NextTurn();
                    break;
                case "callback":
                    if (other[0] == "trapped")
                    {
                        // makemove
                        // 招式失败 好像
                    }
                    break;
                case "poke":
                    if (other[0] == (battle.PlayerPosition == PlayerPosition.Player1 ? "p2" : "p1"))
                    {
                        // 对手的队伍信息
                        var data = other[1].Split(", ");
                        // 0 名字 1 等级
                        await battle.InitOppTeamAsync(data[0]);
                        //battle.OppTeam;
                        // Console.WriteLine(other[1]);
                        //// Console.WriteLine("让我康康");
                    }
                    break;
                case "win":
                    // Console.WriteLine("对战结束");
                    OnBattleEnd?.Invoke(battle, other[0].Contains(ClientInfo.Name));
                    Battles.Remove(battle.Tag);
                    // 对战结束
                    break;
                case "error":
                    OnBattleError?.Invoke(battle, other[0]);
                    // 出现异常
                    break;
                default:
                    battle.LogParse(cmd, other);
                    break;
            }
        }
    }



    private async Task ExcuteMessageAsync(string message, Usage usage = Usage.Standby)
    {
        // Console.WriteLine(message);
        //Debug.WriteLine(message);
        var data = message.Split('|');
        // Console.WriteLine(data[0]);


        if (data[0].Contains("battle"))
        {
            // 对战数据
            // Console.WriteLine("这里是对战...");
            await BattleTagAsync(message, usage);
        }
        else
        {
            switch (data[1])
            {
                case "challstr":
                    //_challId = data[2];
                    //_chall = data[3];

                    ChallInfo = ChallInfo.Create(data[2], data[3]);
                    // 允许登录
                    break;
                case "updateuser":
                    UpdateUser?.Invoke();
                    // 用户更新 可认为登陆完毕（？
                    break;
                case "updatesearch":
                    // 更新房间，json
                    // {"searching":[],"games":{"battle-gen8randombattle-1605790743":"[Gen 8] Random Battle"}}
                    break;
                case "deinit":
                    // 对战结束
                    break;
                case "init":

                    OnBattleRuleInit?.Invoke(message);

                    break;
                case "queryresponse":
                    switch (data[2])
                    {
                        case "roomlist":
                            // 想办法传回去

                            OnGetRoomList?.Invoke(JsonSerializer.Deserialize<Roomlist>(data[3]));

                            break;
                        case "userdetails":
                            OnUserDetails?.Invoke(data[3]);
                            break;
                        default:
                            break;
                    }

                    break;
                case "updatechallenges":
                    if (data[2].Split("\"")[3] != "challengeTo")
                    {
                    }

                    break;
                case "pm":
                    string pmP1 = data[2].Trim(), pmP2 = data[3].Trim();
                    if (data[4].StartsWith('/'))
                    {
                        string[] cmd = data[4].Split(' ');
                        // foreach (var cmdd in cmd)
                        // {
                        //     // Console.WriteLine(cmdd);
                        // }
                        switch (cmd[0])
                        {
                            case "/challenge":
                                if (cmd.Length == 1)
                                {
                                    WriteLogAsync($"{pmP2}取消挑战", MsgType.Receive);
                                    break;
                                }

                                string rule = cmd[1];
                                string rule2 = data[5];
                                // // Console.WriteLine($"rule2: {rule}");
                                if (pmP1 == ClientInfo.Name)
                                {
                                    WriteLogAsync($"发起对{pmP2}挑战, 规则：{rule}", MsgType.Receive);
                                }
                                else
                                {
                                    WriteLogAsync($"收到{pmP1}挑战, 规则：{rule}", MsgType.Receive);
                                    // 触发挑战事件
                                    OnChallenge?.Invoke(pmP1, rule);
                                }

                                break;
                            case "/log":
                                break;
                            default:
                                break;
                        }
                    }
                    else
                    {
                        // 聊天信息
                        WriteLogAsync($"[聊天信息] {pmP1} -> {pmP2}: {data[4]}", MsgType.Receive);
                        if (pmP2 == ClientInfo.Name)
                        {
                            OnChat?.Invoke(pmP1, data[4]);
                        }
                    }

                    if (data[2].Trim() == ClientInfo.Name)
                    {
                        // 我发起的挑战
                    }

                    break;

                default:
                    break;
            }
        }
        // if (data[0].Contains("battle"))
        // {
        //     // 为对战数据
        // }
    }


}

public class Roomlist
{
    public Dictionary<string, RoomPlayer> Rooms { get; set; } = [];
}
public class RoomPlayer
{
    public string p1 { get; set; }
    public string p2 { get; set; }
}