// Generated by Copilot
using System.ComponentModel.DataAnnotations;

namespace PSClient;

/// <summary>
/// 玩家位置枚举，用于标识在对战中的角色
/// </summary>
public enum PlayerPosition
{
    [Display(Name = "p1")]
    Player1,
    [Display(Name = "p2")]
    Player2,
}

/// <summary>
/// 对战状态枚举
/// </summary>
public enum BattleStatus
{
    Waiting,
    Requests,
    Error,
    End,
    TurnFinish,
    GameFinish,
}

/// <summary>
/// 对战结果枚举
/// </summary>
public enum BattleResult
{
    Player1Win,
    Player2Win,
    Draw,
}

/// <summary>
/// 客户端使用状态
/// </summary>
public enum ClientUsage
{
    Standby = 0,
    ChallOwner = 1,
    Search = 2,
}
