param(
    [string]$SourceDir = (Join-Path $PSScriptRoot '..\DatabaseTool\bin\Debug\net8.0\homedata'),
    [string]$OutputPath = (Join-Path $PSScriptRoot '..\Poke.DamageCalc.Blazor\Services\BilingualNameData.g.cs')
)

$ErrorActionPreference = 'Stop'

function Read-NameData([string]$fileName) {
    $path = Join-Path $SourceDir $fileName
    if (-not (Test-Path -LiteralPath $path)) {
        throw "Missing bilingual source file: $path"
    }

    Get-Content -LiteralPath $path -Raw | ConvertFrom-Json
}

function CsLiteral([string]$value) {
    $escaped = $value.
        Replace('\', '\\').
        Replace('"', '\"').
        Replace("`r", '\r').
        Replace("`n", '\n').
        Replace("`t", '\t')

    '"' + $escaped + '"'
}

function Write-Entries($items) {
    foreach ($item in $items) {
        if ([string]::IsNullOrWhiteSpace($item.Name_Eng) -or [string]::IsNullOrWhiteSpace($item.Name_Chs)) {
            continue
        }

        "        new($(CsLiteral $item.Name_Eng), $(CsLiteral $item.Name_Chs)),"
    }
}

function Read-FormNameData([string]$fileName) {
    $path = Join-Path $SourceDir $fileName
    if (-not (Test-Path -LiteralPath $path)) {
        throw "Missing bilingual source file: $path"
    }

    $root = Get-Content -LiteralPath $path -Raw | ConvertFrom-Json
    $forms = New-Object System.Collections.Generic.List[object]
    foreach ($speciesProperty in $root.PSObject.Properties) {
        foreach ($formProperty in $speciesProperty.Value.PSObject.Properties) {
            $form = $formProperty.Value
            if ([string]::IsNullOrWhiteSpace($form.Name_Eng) -or [string]::IsNullOrWhiteSpace($form.Name_Chs)) {
                continue
            }

            $forms.Add($form)
        }
    }

    $forms
}

$species = Read-NameData 'pokenameall.json'
$forms = Read-FormNameData 'formnameall.json'
$moves = Read-NameData 'wazanameall.json'
$items = Read-NameData 'itemnameall.json'
$abilities = Read-NameData 'tokuseinameall.json'
$speciesEntries = (Write-Entries $species) -join [Environment]::NewLine
$formEntries = (Write-Entries $forms) -join [Environment]::NewLine
$moveEntries = (Write-Entries $moves) -join [Environment]::NewLine
$itemEntries = (Write-Entries $items) -join [Environment]::NewLine
$abilityEntries = (Write-Entries $abilities) -join [Environment]::NewLine

$content = @"
// <auto-generated />
namespace Poke.DamageCalc.Blazor.Services;

internal static class BilingualNameData
{
    internal static readonly LocalizedName[] Species =
    [
$speciesEntries
    ];

    internal static readonly LocalizedName[] Forms =
    [
$formEntries
    ];

    internal static readonly LocalizedName[] Moves =
    [
$moveEntries
    ];

    internal static readonly LocalizedName[] Items =
    [
$itemEntries
    ];

    internal static readonly LocalizedName[] Abilities =
    [
$abilityEntries
    ];
}

internal readonly record struct LocalizedName(string English, string Chinese);
"@

$outputDirectory = Split-Path -Parent $OutputPath
New-Item -ItemType Directory -Force -Path $outputDirectory | Out-Null
Set-Content -LiteralPath $OutputPath -Value $content -Encoding utf8NoBOM
