// Generated by Copilot
using System.Text.Json;
using PSClient.Core;
using PSClient.Models;
using PokeCommon.Utils;

namespace PSClient.Battle;

/// <summary>
/// PS对战管理类
/// </summary>
public partial class PSBattle
{
    #region Properties

    /// <summary>
    /// 关联的PS客户端
    /// </summary>
    public PSClient.Client.SDClient Client { get; }

    /// <summary>
    /// 对战状态
    /// </summary>
    public BattleStatus BattleStatus { get; set; }

    /// <summary>
    /// 房间标识
    /// </summary>
    public string RoomTag { get; set; }

    /// <summary>
    /// 当前玩家位置
    /// </summary>
    public PlayerPosition PlayerPosition { get; set; }

    /// <summary>
    /// 玩家1名称
    /// </summary>
    public string Player1Name { get; set; } = string.Empty;

    /// <summary>
    /// 玩家2名称
    /// </summary>
    public string Player2Name { get; set; } = string.Empty;

    /// <summary>
    /// 玩家1队伍
    /// </summary>
    public List<PSBattlePokemon> Player1Team { get; set; } = new();

    /// <summary>
    /// 玩家2队伍
    /// </summary>
    public List<PSBattlePokemon> Player2Team { get; set; } = new();

    /// <summary>
    /// 玩家1场上宝可梦
    /// </summary>
    public PSBattlePokemon[] Player1Side { get; set; } = new PSBattlePokemon[4];

    /// <summary>
    /// 玩家2场上宝可梦
    /// </summary>
    public PSBattlePokemon[] Player2Side { get; set; } = new PSBattlePokemon[4];

    /// <summary>
    /// 当前回合数
    /// </summary>
    public int Turn { get; set; } = 0;

    /// <summary>
    /// 对战索引
    /// </summary>
    public int BattleIndex { get; set; } = 1;

    /// <summary>
    /// 初始化ID
    /// </summary>
    public int InitId { get; set; } = 0;

    /// <summary>
    /// 活跃状态数组
    /// </summary>
    public bool[] ActiveStates { get; set; } = new bool[6];

    /// <summary>
    /// 活跃状态JSON元素
    /// </summary>
    public JsonElement[] ActiveStatusElements { get; set; } = new JsonElement[2];

    #endregion

    #region Computed Properties

    /// <summary>
    /// 对手队伍
    /// </summary>
    public List<PSBattlePokemon> OpponentTeam => 
        PlayerPosition == PlayerPosition.Player1 ? Player2Team : Player1Team;

    /// <summary>
    /// 我方队伍
    /// </summary>
    public List<PSBattlePokemon> MyTeam => 
        PlayerPosition == PlayerPosition.Player1 ? Player1Team : Player2Team;

    /// <summary>
    /// 我方场上宝可梦
    /// </summary>
    public PSBattlePokemon[] MySide => 
        PlayerPosition == PlayerPosition.Player1 ? Player1Side : Player2Side;

    /// <summary>
    /// 对手场上宝可梦
    /// </summary>
    public PSBattlePokemon[] OpponentSide => 
        PlayerPosition == PlayerPosition.Player1 ? Player2Side : Player1Side;

    #endregion

    #region Constructor

    /// <summary>
    /// 构造函数
    /// </summary>
    /// <param name="client">PS客户端</param>
    /// <param name="roomTag">房间标识</param>
    public PSBattle(PSClient.Client.SDClient client, string roomTag)
    {
        Client = client;
        RoomTag = roomTag;
        
        // 初始化队伍
        Player1Team = Enumerable.Repeat<PSBattlePokemon?>(null, 6).ToList()!;
        Player2Team = Enumerable.Repeat<PSBattlePokemon?>(null, 6).ToList()!;
    }

    #endregion

    #region Public Methods

    /// <summary>
    /// 发送队伍排序指令
    /// </summary>
    /// <param name="order">排序字符串</param>
    public async Task SendTeamOrderAsync(string order)
    {
        await Client.SendTeamOrderAsync(RoomTag, order, Turn);
    }

    /// <summary>
    /// 发送行动指令
    /// </summary>
    /// <param name="chooseDataArray">选择数据数组</param>
    public async Task SendMoveAsync(params ChooseData[] chooseDataArray)
    {
        await Client.SendMoveAsync(RoomTag, Turn, chooseDataArray);
    }

    /// <summary>
    /// 离开房间
    /// </summary>
    public async Task LeaveRoomAsync()
    {
        await Client.SendLeaveAsync(RoomTag);
    }

    /// <summary>
    /// 投降
    /// </summary>
    public async Task ForfeitAsync()
    {
        await Client.SendForfeitAsync(RoomTag);
    }

    /// <summary>
    /// 开启计时器
    /// </summary>
    public async Task SendTimerOnAsync()
    {
        await Client.SendAsync(RoomTag, "/timer on");
    }

    /// <summary>
    /// 发送消息
    /// </summary>
    /// <param name="message">消息内容</param>
    public async Task SendMessageAsync(string message)
    {
        await Client.SendAsync(RoomTag, message);
    }

    #endregion
}
