// Generated by Copilot
using System.ComponentModel.DataAnnotations;

namespace PSClient.Models;

/// <summary>
/// 对战数据模型
/// </summary>
public class BattleData
{
    /// <summary>
    /// 房间ID，作为主键
    /// </summary>
    [Key]
    public string RoomId { get; set; } = string.Empty;

    /// <summary>
    /// 玩家1 ID
    /// </summary>
    public string Player1Id { get; set; } = string.Empty;

    /// <summary>
    /// 玩家2 ID
    /// </summary>
    public string Player2Id { get; set; } = string.Empty;

    /// <summary>
    /// 玩家1分数
    /// </summary>
    public int Player1Score { get; set; } = 0;

    /// <summary>
    /// 玩家2分数
    /// </summary>
    public int Player2Score { get; set; } = 0;

    /// <summary>
    /// 对战结果
    /// </summary>
    public BattleResult Result { get; set; }

    /// <summary>
    /// 对战日志
    /// </summary>
    public string BattleLog { get; set; } = string.Empty;

    /// <summary>
    /// 对战规则/分级
    /// </summary>
    public string Tier { get; set; } = string.Empty;

    /// <summary>
    /// 对战开始时间
    /// </summary>
    public DateTime StartTime { get; set; } = DateTime.Now;

    /// <summary>
    /// 对战结束时间
    /// </summary>
    public DateTime? EndTime { get; set; }

    /// <summary>
    /// 对战持续时间
    /// </summary>
    public TimeSpan? Duration => EndTime?.Subtract(StartTime);
}
