// Generated by Copilot
using PokeCommon.Models;
using PokemonDataAccess.Models;

namespace PSClient.Models;

/// <summary>
/// PS对战中的宝可梦模型
/// </summary>
public class PSBattlePokemon : BattlePokemon
{
    /// <summary>
    /// 构造函数
    /// </summary>
    /// <param name="pokemon">宝可梦基础信息</param>
    /// <param name="psName">PS中的名称</param>
    public PSBattlePokemon(Pokemon pokemon, string psName) : base(pokemon)
    {
        PSName = psName;
    }

    /// <summary>
    /// 在PS中的名称
    /// </summary>
    public string PSName { get; set; }

    /// <summary>
    /// 最大HP值
    /// </summary>
    public int MaxHP { get; set; }

    /// <summary>
    /// 活跃ID（在场上的标识）
    /// </summary>
    public int ActiveId { get; set; } = -1;

    /// <summary>
    /// 是否在指挥状态
    /// </summary>
    public bool IsCommanding { get; internal set; }

    /// <summary>
    /// 是否被困住无法交换
    /// </summary>
    public bool IsTrapped { get; internal set; }

    /// <summary>
    /// 宝可梦失去战斗能力
    /// </summary>
    public void Faint()
    {
        Dynamax = false;
        NowHp = 0;
    }

    /// <summary>
    /// 是否在场上
    /// </summary>
    public bool IsActive => ActiveId >= 0;

    /// <summary>
    /// 是否失去战斗能力
    /// </summary>
    public bool IsFainted => NowHp <= 0;

    /// <summary>
    /// HP百分比
    /// </summary>
    public double HPPercentage => MaxHP > 0 ? (double)NowHp / MaxHP : 0;
}
