// Generated by Copilot
using System.Text.Json;
using System.Text.Json.Serialization;

namespace PSClient.Models;

/// <summary>
/// 用户详细信息模型
/// </summary>
public class UserDetail
{
    /// <summary>
    /// 用户ID
    /// </summary>
    [JsonPropertyName("id")]
    public string? Id { get; set; }

    /// <summary>
    /// 用户唯一标识符
    /// </summary>
    [JsonPropertyName("userid")]
    public string? UserId { get; set; }

    /// <summary>
    /// 用户显示名称
    /// </summary>
    [JsonPropertyName("name")]
    public string? Name { get; set; }

    /// <summary>
    /// 用户头像信息
    /// </summary>
    [JsonPropertyName("avatar")]
    public JsonElement? Avatar { get; set; }

    /// <summary>
    /// 用户组
    /// </summary>
    [JsonPropertyName("group")]
    public string? Group { get; set; }

    /// <summary>
    /// 是否自动确认
    /// </summary>
    [JsonPropertyName("autoconfirmed")]
    public bool AutoConfirmed { get; set; }

    /// <summary>
    /// 用户所在房间信息
    /// </summary>
    [JsonPropertyName("rooms")]
    public JsonElement Rooms { get; set; }
}

/// <summary>
/// 房间列表模型
/// </summary>
public class RoomList
{
    /// <summary>
    /// 房间字典，键为房间ID，值为房间玩家信息
    /// </summary>
    public Dictionary<string, RoomPlayer> Rooms { get; set; } = new();
}

/// <summary>
/// 房间玩家信息
/// </summary>
public class RoomPlayer
{
    /// <summary>
    /// 玩家1名称
    /// </summary>
    public string Player1 { get; set; } = string.Empty;

    /// <summary>
    /// 玩家2名称
    /// </summary>
    public string Player2 { get; set; } = string.Empty;
}

/// <summary>
/// 排名数据模型
/// </summary>
public class RankData
{
    /// <summary>
    /// ELO评级
    /// </summary>
    [JsonPropertyName("elo")]
    public double ELO { get; set; }

    /// <summary>
    /// 格式ID
    /// </summary>
    [JsonPropertyName("formatid")]
    public string FormatId { get; set; } = string.Empty;
}
