// Generated by Copilot
namespace PSClient.Exceptions;

/// <summary>
/// PS客户端异常基类
/// </summary>
public class PSClientException : Exception
{
    public PSClientException() : base() { }
    
    public PSClientException(string message) : base(message) { }
    
    public PSClientException(string message, Exception innerException) : base(message, innerException) { }
}

/// <summary>
/// 连接异常
/// </summary>
public class PSConnectionException : PSClientException
{
    public PSConnectionException() : base("Failed to connect to Pokemon Showdown server") { }
    
    public PSConnectionException(string message) : base(message) { }
    
    public PSConnectionException(string message, Exception innerException) : base(message, innerException) { }
}

/// <summary>
/// 认证异常
/// </summary>
public class PSAuthenticationException : PSClientException
{
    public PSAuthenticationException() : base("Authentication failed") { }
    
    public PSAuthenticationException(string message) : base(message) { }
    
    public PSAuthenticationException(string message, Exception innerException) : base(message, innerException) { }
}

/// <summary>
/// 对战异常
/// </summary>
public class PSBattleException : PSClientException
{
    public string? RoomId { get; }
    
    public PSBattleException(string? roomId = null) : base("Battle error occurred") 
    {
        RoomId = roomId;
    }
    
    public PSBattleException(string message, string? roomId = null) : base(message) 
    {
        RoomId = roomId;
    }
    
    public PSBattleException(string message, Exception innerException, string? roomId = null) : base(message, innerException) 
    {
        RoomId = roomId;
    }
}

/// <summary>
/// 命令异常
/// </summary>
public class PSCommandException : PSClientException
{
    public string? Command { get; }
    
    public PSCommandException(string? command = null) : base("Command execution failed") 
    {
        Command = command;
    }
    
    public PSCommandException(string message, string? command = null) : base(message) 
    {
        Command = command;
    }
    
    public PSCommandException(string message, Exception innerException, string? command = null) : base(message, innerException) 
    {
        Command = command;
    }
}
